export const Message = {
  TAI_KHOAN_TON_TAI: "TAI_KHOAN_TON_TAI",
  DANG_KY_THANH_CONG: "DANG_KY_THANH_CONG",
  DANG_NHAP_THANH_CONG: "DANG_NHAP_THANH_CONG",
  LOI_SERVER: "LOI_SERVER",
  TAI_KHOAN_OR_MK_SAI: "TAI_KHOAN_OR_MK_SAI",
  KHONG_CO_QUYEN_TRUY_CAP: "KHONG_CO_QUYEN_TRUY_CAP",
  GUI_FEED_BACK_THANH_CONG: "GUI FEEDBACK THANH CONG",
  THIEU_THONG_TIN_FEED_BACK: "THIEU THONG TIN FEED BACK",
  THANH_CONG: "THANH CONG"
}